hmm_predict=function(model1,sample_sent,sepchar=" ",addsmooth=1)
{
	print(sample_sent)
	seq=model1$tseq_count
	print(seq)
	seq=sweep(seq,1,rep(addsmooth,4),"+")
	print(seq)
	seq=sweep(seq,1,sum(seq),"/")
	print(seq)
	seq=log(seq)
	ct=model1$ct_count
	ct=sweep(ct,1,rep(addsmooth,nrow(ct)),"+")
	print(ct)
	ct=sweep(ct,1,sum(ct),"/")
	ct=log(ct)
	print(dim(ct))
	prior=model1$tprior_count
	prior=sweep(prior,1,rep(addsmooth,4),"+")
	prior=sweep(prior,1,sum(prior),"/")
	prior=log(prior)
	print(prior)
	Tags=c()
	Words=c()
	for(i in 1:length(sample_sent))
	{
		utf8_temp=utf8ToInt(sample_sent[i])
		real_process=as.matrix(prior[,])
		result=""
		print(nchar(sample_sent[i]))
		if(nchar(sample_sent[i])!=1)
		{
			fi=matrix("",nrow=nchar(sample_sent[i])-1,ncol=4)
			for(j in 1:(nchar(sample_sent[i])-1))
			{
			#print(utf8_temp)
			#print(nchar(sample_sent[i]))
			#print(utf8_temp[j])
			print("WORD")
			print(ct[utf8_temp[j],])
			print("REAL_PROCESS")
			print(t(real_process))
			pre=c(ct[utf8_temp[j],]+t(real_process))
			print("PRE")
			print(pre)
	
			#print(seq)
			process=sweep(seq,1,pre,"+")
			print("REAL")
			print(real_process)
			print("seq")
			print(seq)
			print("PRO")
			print(process)
			#print(seq)
			for(k in 1:4)
			{
				index=which(process[,k]== max(process[,k]), arr.ind = TRUE)
				print(index)
				if(index==1)
				{
					fi[j,k]="S"
					real_process[k,1]=process[1,k]
				}
				if(index==2)
				{
					fi[j,k]="B"
					real_process[k,1]=process[2,k]
				}
				if(index==3)
				{
					fi[j,k]="M"
					real_process[k,1]=process[3,k]
				}
				if(index==4)
				{
					#print("HI")
					fi[j,k]="E"
					real_process[k,1]=process[4,k]
				}
			}
			}
		}
		last=ct[utf8_temp[nchar(sample_sent[i])],]+t(real_process)
		print(last)
		last_symbol=""
		index=which.max(last)
		print(index)
		if(index==1)				
		{				
			last_symbol="S"
		}
		if(index==2)				
		{
			last_symbol="B"
		}
		if(index==3)
		{
			last_symbol="M"
		}
		if(index==4)
		{
			last_symbol="E"
		}
		result=last_symbol
		if(nchar(sample_sent[i])!=1)
		{
		for(m in nrow(fi):1)
		{

			print(m)
			if(last_symbol=="S")
			{
				last_symbol=fi[m,1]
				result=paste(last_symbol,result,sep="")
				next
			}
			if(last_symbol=="B")
			{
				last_symbol=fi[m,2]
				result=paste(last_symbol,result,sep="")
				next
			}
			if(last_symbol=="M")
			{
				last_symbol=fi[m,3]
				result=paste(last_symbol,result,sep="")
				next
			}
			if(last_symbol=="E")
			{
				last_symbol=fi[m,4]
				result=paste(last_symbol,result,sep="")
				next
			}
		}
		}
		result_string=""
		for(k in 1:(nchar(result)-1))
		{
			print(k)
			x=sample_sent[i]
			temp=substr(x,k,k)
			result_string=paste(result_string,temp,sep="")
			A=substr(result,k,k)
			if(A=="E" || A=="S")
			{
				result_string=paste(result_string,sepchar,sep="")
			}
		}
		x=sample_sent[i]
		result_string=paste(result_string,substr(x,nchar(result),nchar(result)),sep="")
		print(fi)
		print(result)
		Tags=append(Tags,result)
		Words=append(Words,result_string)
	}
	print(Tags)
	print(Words)
	ret=list(outsent=Words,outtag=Tags)
	return(ret)
}

hmm_train=function(text,tag)
{
	tprior_count=matrix(0,ncol=1,nrow=4)
	tseq_count=matrix(0,ncol=4,nrow=4)
	ct_count=matrix(0,ncol=4,nrow=70000)
	for(i in 1:length(tag))
	{
		BMES_temp=""
		last_BMSE_temp=""
		if(text[i]=="")
		{
			next
		}
		utf8_temp=utf8ToInt(text[i])
		#print(utf8_temp)
		for(j in 1:nchar(tag[i]))
		{
			BMES_temp=substr(tag[i],j,j)
			if(BMES_temp=="S")
			{
				tprior_count[1,1]=tprior_count[1,1]+1
				ct_count[utf8_temp[j],1]=ct_count[utf8_temp[j],1]+1
				#if(i!=1)
				#{
					if(last_BMSE_temp=="S")
					{
						tseq_count[1,1]=tseq_count[1,1]+1
					}
					if(last_BMSE_temp=="B")
					{
						tseq_count[2,1]=tseq_count[2,1]+1
					}
					if(last_BMSE_temp=="M")
					{
						tseq_count[3,1]=tseq_count[3,1]+1
					}
					if(last_BMSE_temp=="E")
					{
						tseq_count[4,1]=tseq_count[4,1]+1
					}
			#	}
			}
			if(BMES_temp=="B")
			{
				tprior_count[2,1]=tprior_count[2,1]+1
				ct_count[utf8_temp[j],2]=ct_count[utf8_temp[j],2]+1
				#if(i!=1)
				#{
					if(last_BMSE_temp=="S")
					{
						tseq_count[1,2]=tseq_count[1,2]+1
					}
					if(last_BMSE_temp=="B")
					{
						tseq_count[2,2]=tseq_count[2,2]+1
					}
					if(last_BMSE_temp=="M")
					{
						tseq_count[3,2]=tseq_count[3,2]+1
					}
					if(last_BMSE_temp=="E")
					{
						tseq_count[4,2]=tseq_count[4,2]+1
					}
				#}
			}
			if(BMES_temp=="M")
			{
				tprior_count[3,1]=tprior_count[3,1]+1
				ct_count[utf8_temp[j],3]=ct_count[utf8_temp[j],3]+1
				#if(i!=1)
				#{
					if(last_BMSE_temp=="S")
					{
						tseq_count[1,3]=tseq_count[1,3]+1
					}
					if(last_BMSE_temp=="B")
					{
						tseq_count[2,3]=tseq_count[2,3]+1
					}
					if(last_BMSE_temp=="M")
					{
						tseq_count[3,3]=tseq_count[3,3]+1
					}
					if(last_BMSE_temp=="E")
					{
						tseq_count[4,3]=tseq_count[4,3]+1
					}
				#}
			}
			if(BMES_temp=="E")
			{
				tprior_count[4,1]=tprior_count[4,1]+1
				ct_count[utf8_temp[j],4]=ct_count[utf8_temp[j],4]+1
				#if(i!=1)
				#{
					if(last_BMSE_temp=="S")
					{
						tseq_count[1,4]=tseq_count[1,4]+1
					}
					if(last_BMSE_temp=="B")
					{
						tseq_count[2,4]=tseq_count[2,4]+1
					}
					if(last_BMSE_temp=="M")
					{
						tseq_count[3,4]=tseq_count[3,4]+1
					}
					if(last_BMSE_temp=="E")
					{
						tseq_count[4,4]=tseq_count[4,4]+1
					}
				#}
			}
			last_BMSE_temp=BMES_temp
		}
	}
	ret=list(ct_count=ct_count,tseq_count=tseq_count,tprior_count=tprior_count)
	return(ret)
}


setwd('/Users/StanleyLIn/Downloads/upload_hw6')
load('cwsas_train_v2.rdata')
model1=hmm_train(train_sent$text2, train_sent$bmes_tag)
out2=hmm_predict(model1, sample_sent)
