hmm_train=function(text,tag)
{
	tprior_count=matrix(0,ncol=1,nrow=4)
	tseq_count=matrix(0,ncol=4,nrow=4)
	ct_count=matrix(0,ncol=4,nrow=70000)
	for(i in 1:length(tag))
	{
		BMES_temp=""
		last_BMSE_temp=""
		if(text[i]=="")
		{
			next
		}
		utf8_temp=utf8ToInt(text[i])
		#print(utf8_temp)
		for(j in 1:nchar(tag[i]))
		{
			BMES_temp=substr(tag[i],j,j)
			if(BMES_temp=="S")
			{
				tprior_count[1,1]=tprior_count[1,1]+1
				ct_count[utf8_temp[j],1]=ct_count[utf8_temp[j],1]+1
				#if(i!=1)
				#{
					if(last_BMSE_temp=="S")
					{
						tseq_count[1,1]=tseq_count[1,1]+1
					}
					if(last_BMSE_temp=="B")
					{
						tseq_count[2,1]=tseq_count[2,1]+1
					}
					if(last_BMSE_temp=="M")
					{
						tseq_count[3,1]=tseq_count[3,1]+1
					}
					if(last_BMSE_temp=="E")
					{
						tseq_count[4,1]=tseq_count[4,1]+1
					}
			#	}
			}
			if(BMES_temp=="B")
			{
				tprior_count[2,1]=tprior_count[2,1]+1
				ct_count[utf8_temp[j],2]=ct_count[utf8_temp[j],2]+1
				#if(i!=1)
				#{
					if(last_BMSE_temp=="S")
					{
						tseq_count[1,2]=tseq_count[1,2]+1
					}
					if(last_BMSE_temp=="B")
					{
						tseq_count[2,2]=tseq_count[2,2]+1
					}
					if(last_BMSE_temp=="M")
					{
						tseq_count[3,2]=tseq_count[3,2]+1
					}
					if(last_BMSE_temp=="E")
					{
						tseq_count[4,2]=tseq_count[4,2]+1
					}
				#}
			}
			if(BMES_temp=="M")
			{
				tprior_count[3,1]=tprior_count[3,1]+1
				ct_count[utf8_temp[j],3]=ct_count[utf8_temp[j],3]+1
				#if(i!=1)
				#{
					if(last_BMSE_temp=="S")
					{
						tseq_count[1,3]=tseq_count[1,3]+1
					}
					if(last_BMSE_temp=="B")
					{
						tseq_count[2,3]=tseq_count[2,3]+1
					}
					if(last_BMSE_temp=="M")
					{
						tseq_count[3,3]=tseq_count[3,3]+1
					}
					if(last_BMSE_temp=="E")
					{
						tseq_count[4,3]=tseq_count[4,3]+1
					}
				#}
			}
			if(BMES_temp=="E")
			{
				tprior_count[4,1]=tprior_count[4,1]+1
				ct_count[utf8_temp[j],4]=ct_count[utf8_temp[j],4]+1
				#if(i!=1)
				#{
					if(last_BMSE_temp=="S")
					{
						tseq_count[1,4]=tseq_count[1,4]+1
					}
					if(last_BMSE_temp=="B")
					{
						tseq_count[2,4]=tseq_count[2,4]+1
					}
					if(last_BMSE_temp=="M")
					{
						tseq_count[3,4]=tseq_count[3,4]+1
					}
					if(last_BMSE_temp=="E")
					{
						tseq_count[4,4]=tseq_count[4,4]+1
					}
				#}
			}
			last_BMSE_temp=BMES_temp
		}
	}
	ret=list(ct_count=ct_count,tseq_count=tseq_count,tprior_count=tprior_count)
	return(ret)
}
